name: klarifikasi_id
description: "Aplikasi klarifikasi hoaks dengan Flutter dan Laravel backend."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  collection: ^1.18.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Font configuration untuk SpotifyMix
  fonts:
    - family: SpotifyMix
      fonts:
        - asset: assets/font/SpotifyMix-Regular.ttf
        - asset: assets/font/SpotifyMix-Thin.ttf
          weight: 100
        - asset: assets/font/SpotifyMix-Light.ttf
          weight: 300
        - asset: assets/font/SpotifyMix-Medium.ttf
          weight: 500
        - asset: assets/font/SpotifyMix-Bold.ttf
          weight: 700
        - asset: assets/font/SpotifyMix-Extrabold.ttf
          weight: 800
        - asset: assets/font/SpotifyMix-Black.ttf
          weight: 900
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/font/

