name: klarifikasi_id
description: "Aplikasi klarifikasi hoaks dengan Flutter dan Laravel backend."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  collection: ^1.18.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
